def create_newsletter_content(tickers: list[str]) -> str:
    """Create the newsletter content."""
    content = f"""
    <html>
    <body>
        <h2>Portfolio Newsletter</h2>
        <p>Here's your daily portfolio update for: <strong>{", ".join(tickers)}</strong></p>

        <h3>Stock Updates</h3>
        <ul>
    """

    for ticker in tickers:
        content += f"<li>{ticker}: Market analysis coming soon...</li>\n"

    content += """
        </ul>

        <p><em>This is an automated newsletter generated by your Portfolio Newsletter service.</em></p>
    </body>
    </html>
    """

    return content.strip()
